apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ramengo
  name: ramengo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ramengo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ramengo
    spec:
      containers:
        - args:
            - go
            - run
            - cmd/main.go
          env:
            - name: API_KEY
              value: 78c15bef-829f-4ee6-97c2-6707a94394b0
            - name: AṔI_PORT
              value: "8080"
            - name: MYSQL_DATABASE
              value: ramenGo
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: thyagopereira/ramengo:latest
          name: ramengo
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: ramengo-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: ramengo-cm0
          name: ramengo-cm0
